name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Checker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: BuildStandard
        run: make
      
      
      - uses: actions/setup-ruby@v1
      - name: Send Webhook Notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_GITHUB_ACTION: ${{ secrets.WEBHOOK_GITHUB_ACTION }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        shell: bash
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_GITHUB_ACTION
  tests:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: BuildTest
        shell: bash
        run: |
          git clone --recursive https://github.com/Snaipe/Criterion
          meson build
          ninja -C build
          ninja -C build install
          make tests_run

  deploy:
    name: Deploy
    needs: [build, tests]
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up ssh key
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: |
            ${{ secrets.EPITECH_DEPLOYMENT }}
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: '0' # get all history of master


      #Push on an epitech repository
      - name: Add host git.epitech.eu
        shell: bash
        run: ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts

      - name: Set up remote (epitech)
        shell: bash
        run: |
          git remote add epitech git@git.epitech.eu:valentin.mille@epitech.eu/CCP_plazza_2019/
      - name : Push to repository (epitech)
        shell: bash
        run: |
          git push epitech master
